### PR TITLE
update lcobucci/jwt dependency to support ^3.3 or ^4.0

### PR DESCRIPTION
**Pull request by jackdpeterson**

### CODE REVIEW

**Comment by tgalopin** [comment]
Could you put both major versions? We probably support both :) .

**Comment by jackdpeterson** [comment]
Happy to do so.

**Comment by tgalopin** [comment]
Ah, I just realized you did this PR on acmephp/core! Sorry, but could you open it on https://github.com/acmephp/acmephp ? This repository is a read-only subtree split.

**Comment by jackdpeterson** [comment]
Thanks @tgalopin -- new PR located at https://github.com/acmephp/acmephp/pull/224

**Pull request closed without merging**
